#!/bin/sh -eu

if ! command -v brew >/dev/null 2>&1; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOME/.Brewfile" ]; then
  brew bundle --file $HOME/.Brewfile
fi

if [ "$(uname)" = "Darwin" ]; then
  ## defaults ##
  # Show all file extensions
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true

  # US 入力モードでキー長押しでアクセント選択ポップアップが表示されるのを無効にする
  defaults write -g ApplePressAndHoldEnabled -bool false

  # 入力補助系の無効化
  defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
  defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
  defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
  defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
  defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

  # Disable "Automatically rearrange spaces based on most recent use"
  defaults write com.apple.dock 'mru-spaces' -bool false

  # Dim hidden apps
  defaults write com.apple.Dock showhidden -bool true

  # Restart affected applications
  for app in "Finder" "Dock" "SystemUIServer"; do
    killall "${app}" &> /dev/null || true
  done

  ## Startup items ##
  # noTunes
  osascript -e 'tell application "System Events" to make login item at end with properties { path: "/Applications/noTunes.app", hidden: false }'
fi
